Attendance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
from users import views
from attend.views import sync_attendance_all, sync_user
# from attend.views import Manual_date_input
from deviceusers.views import device_user_edit
schema_view = get_swagger_view(title='Attendance API')
# from .views import DeviceUserListView
from deviceusers.views import DeviceUserListView
from attend.views import all_transaction,approvalList
from attend.views import all_attendance_report

urlpatterns = [
    path('admin/', admin.site.urls),


    # Webapp url
    path('',views.index,name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('approval-list/', approvalList, name='approval-list'),


    # service url
    path('sync-user/', sync_user, name='sync-user'),
    path('sync-attendance/', sync_attendance_all, name='sync-attendance'),
    path('edit/', device_user_edit, name='user-edit'),




    # App url
    re_path('', include('users.urls')),
    re_path('', include('attend.urls')),
    re_path('', include('deviceusers.urls')),
    re_path('', include('rules.urls')),

    # API Documentation url
    path('api/swagger-doc', schema_view),
    path('api/core-doc', include_docs_urls(title='Coredoc Attendance API')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deviceusers/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from .views import DeviceUserApiView, DeviceUserUpdate, DeviceUserListView
from rest_framework import routers



router = routers.DefaultRouter()
router.register('device-users', DeviceUserApiView)


urlpatterns = [
    path('api/device-users/', include(router.urls)),
    path('device-user-edit/', DeviceUserUpdate.as_view(),name='device-user-edit'),
    path('device-user-list/', DeviceUserListView.as_view(),name='device-user-list'),


]

rules/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from rest_framework import routers

from .views import OfficeRulesApiView, LateRulesApiView, RulesExceptionApiView, office_rules_get_create, create_exception, create_late_limit

router = routers.DefaultRouter()
router.register('office-rules', OfficeRulesApiView)
router.register('late-rules', LateRulesApiView)
router.register('exception-rules', RulesExceptionApiView)

urlpatterns = [
    path('api/rules/', include(router.urls)),
    path('office-rules/', office_rules_get_create, name='office-rules'),
    path('create-exception/', create_exception, name='exception'),
    path('create-late/', create_late_limit, name='late'),
]

attend/models.py
from django.db import models
from deviceusers.models import Device_user

class Attendance(models.Model):
    class Meta:
        unique_together = ['user_id', 'datetime']
        ordering = ('-datetime',)

    Auto = 'Auto'
    Manual = 'Manual'
    Ontime = 'On Time'
    Late = 'Late'
    APPROVAL_CHOICES = (
        (Auto,'Auto'),
        (Manual,'Manual')
    )
    LATE_CHOICES = (
        (Ontime,'On Time'),
        (Late,'Late')
    )

    user_id = models.ForeignKey(Device_user, null=True, on_delete=models.CASCADE)
    datetime = models.DateTimeField()
    approval_status = models.CharField(max_length=20, choices=APPROVAL_CHOICES, default=Auto)
    late_status = models.CharField(max_length=20, choices=LATE_CHOICES, default=Ontime)

    def __str__(self):
        return ("user: " + str(self.user_id) + '  ' + "Date: " +str(self.datetime.strftime("%A %d %b %Y %H:%M:%S")))

#Approval Table model
class ApprovalTable(models.Model):
    class Meta:
        unique_together = ['user_id', 'datetime']
        ordering = ('-datetime',)


    user_id = models.ForeignKey(Device_user, null=True, on_delete=models.CASCADE)
    datetime = models.DateTimeField()
    reason = models.TextField()

    Approved = 'Approved'
    Pending = 'Pending'
    Rejected = 'Rejected'
    STATUS_CHOICES = (
        (Approved, 'Approved'),  # First element is value, Second element is human readable representation of the value
        (Pending, 'Pending'),
        (Rejected, 'Rejected'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=Pending)
    def __str__(self):
        return ("User Name: " + str(self.user_id) + '       ' + "Date: " +str(self.datetime))

#model for approval history
class ApprovalHistory(models.Model):

    # approval_id = models.ForeignKey(ApprovalTable, null=True, on_delete=models.CASCADE)
    user_id = models.IntegerField()
    datetime = models.DateTimeField()
    reason = models.TextField()
    action_type = models.TextField()
    action_time = models.DateTimeField()
    action_by = models.TextField()
    def __str__(self):
        return ("Approval Type: " + str(self.type) + '       ' + "Date: " +str(self.datetime))



class AttendanceReport(models.Model):
    class Meta:
        unique_together = ['user', 'date']
        ordering = ('-date',)

    date = models.DateField()
    user = models.ForeignKey(Device_user, null=True, on_delete=models.CASCADE)
    intime = models.TimeField()
    outtime = models.TimeField()
    total_time = models.CharField(max_length=255)
    approval_status = models.CharField(max_length=255)
    is_late = models.BooleanField(default=False)
    remarks = models.TextField(default="",blank=True)



    def __str__(self):
        return (str(self.user.name) + '       ' + "Date: " +str(self.date))

deviceusers/models.py
from django.db import models


# Create your models here.
class Device_user(models.Model):
    class Meta:
        ordering = ('user_id',)
    user_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30,default="Unknown")
    password = models.CharField(max_length=255,blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return  str(self.user_id) + '   ' +  self.name

deviceusers/views.py
from rest_framework import viewsets
from .models import Device_user
from .deviceusers_serializers import DeviceUserSerializer
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from .services.edit_device_user import edit_device_user
from attend.service.fetch_user import sync_all_user
from attend.models import Attendance


# Create your views here.
class DeviceUserApiView(viewsets.ModelViewSet):
    queryset = Device_user.objects.all()
    serializer_class = DeviceUserSerializer
#view for editing user
def device_user_edit(request):
    if request.method == "POST":
        name = request.POST.get("device_username")
        uid = request.POST.get("id")
        edit_device_user(uid,name)
        sync_all_user()
    return redirect("device-user-list")
#view for updating user
class DeviceUserUpdate(TemplateView):
    template_name = 'user_edit_form.html'
    success_url = 'device-user-edit/'
#view for showing the list of users
class DeviceUserListView(ListView):
    template_name = 'device_user_list.html'
    queryset = Device_user.objects.all()
    context_object_name = 'users'

deviceusers/templates/device_user_list.html
{% extends 'dashboard.html' %}
{% block content %}
    <div class="page-wrapper">
        <div class="content container-fluid">

            <!-- Page Title -->
            <div class="row">
                <div class="col-sm-8 col-6">
                    <h4 class="page-title">Device Users</h4>
                </div>
                <div class="col-sm-4 col-6 text-right">
                    <a href="#" class="btn add-btn" data-toggle="modal" data-target="#create-user"><i
                            class="fa fa-plus"></i>Edit Device User</a>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <!-- Search Filter -->
                    <div class="row filter-row">
                        <div class="col-sm-3 col-md-3 col-lg-3"></div>

                        <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    </div>
                    <!-- /Search Filter -->
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered custom-table mb-0 datatable">
                                <thead class="thead-dark">
                                <tr>
                                    <th>ID</th>
                                    <th>Device User Name</th>
                                    <th>Status</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for user in users %}
                                    <tr>
                                        <td>{{ user.user_id }}</td>
                                        <td>{{ user.name }}</td>
                                        {% if user.active %}
                                            <td><span class="badge badge-success">Active</span></td>
                                        {% else %}
                                            <td><span class="badge badge-danger">Deactive</span></td>

                                        {% endif %}

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- create-user -->
        <div id="create-user" class="modal custom-modal fade" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit Device User</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method='POST' action="/edit/" >
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <label>User Name</label>
                                    <input class="form-control" name='device_username' placeholder='Name'/>
                                </div>
                                <div class="form-group col-sm-6">
                                    <label>Id</label>
                                    <input class="form-control" type='text' name='id' placeholder='id' />
                                </div>
                            </div>
                            <div class="submit-section">
                                <button class="btn btn-primary submit-btn" type="submit">Edit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Add Overtime Modal -->


    </div>
<script>

    var element = document.getElementById("device-user");
    element.classList.add("active");

</script>
{% endblock %}

deviceusers/templates/user_edit_form.html
{% extends 'base.html' %}
{% block body_block %}
    {{ form.date }}
    <div class="container">
        <div class="jumbotron">
            <h1>Manual Date Input :</h1>

            <form method='POST' action="/edit/" >
                {% csrf_token %}
                <input type='text' name='device_username' placeholder='Name'/><br/>
                <input type='text' name='id' placeholder='id' /><br/>
                <input type='submit' value='edit' />
            </form>

        </div>
    </div>
    <script>
        $(function () {
            $("#id_datetime").datetimepicker({
                format: 'd/m/Y H:i',
            });
        });
    </script>

{% endblock %}